URL_SERVICE = " https://cnt-d9bfdb93-1748-405f-98dc-212240ca29d9.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH= "/api/v1/users"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"